name: auto-deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: ğŸ§‘ğŸ»â€ğŸ’» checkout source code
        uses: actions/checkout@v2.3.4

      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: ğŸ˜ Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"

      - name: ğŸ•¸ install dependencies on ubuntu
        run: npm install

      - name: ğŸ¢ build
        run: npm rub build

      - name: ğŸ‘ŠğŸ» deploy
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.API_KEY }}
        with:
          build_dir: public
          branch: main
