on:
  push:
    branches:
      - main

name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: npm install
        run: npm install

      - name: gatsby build
        env:
          GH_API_KEY: ${{ secrets.API_KEY }}
        run: npm run build

      - name: ğŸ‘ŠğŸ» deploy
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.API_KEY }}
        with:
          build_dir: public
          branch: main
